[package]
name = "rsbind"
version = "0.1.0"
authors = ["sidney.wang <sidney.wang@foxmail.com>"]

[dependencies]
quote = "0.6"
proc-macro2 = "0.4.30"
cbindgen = "0.9.0"
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
zip = "0.5.2"
fs_extra = "1.1.0"
toml = "0.5.1"
jni = { git = "https://github.com/prevoty/jni-rs" }
error-chain = "0.12.1"
genco = {git = "https://github.com/shunding/genco", branch="master"}

[dependencies.syn]
version = "0.15.39"
default_features = false
features = ["parsing", "full", "extra-traits"]

[lib]
name = "rsbind_core"
path = "src/lib.rs"

[[bin]]
name = "rsbind"
path = "src/main.rs"
